name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Upload Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          EXT=""
          if [ "${GOOS}" = "windows" ]; then EXT=".exe"; fi
          go build -trimpath -ldflags="-s -w" -o dist/httping-ng-${GOOS}-${GOARCH}${EXT} ./cmd/httping

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
